import {
  faLock, faPenToSquare, faLightbulb, faRobot, faLandmark,
  faBox, faBriefcase, faCloudSun, faGlobe, faRocket,
  faBullseye, faChartBar, faWrench, faLaptopCode, faStar,
  faInbox, faUserTie, faMugHot, faPersonRunning, faCamera,
  faBookOpen, faGamepad, faEnvelope, faClock, faFileLines,
  faLink, faImage, faUser, faFolderOpen, faFile,
  faArrowUpRightFromSquare, faAngleRight, faChartSimple,
  faDatabase, faCode, faServer, faLayerGroup, faGraduationCap,
  faHeart, faShieldHalved, faTerminal, faPalette,
} from '@fortawesome/free-solid-svg-icons'
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'

export const ICON_MAP: Record<string, IconDefinition> = {
  'lock':                    faLock,
  'pen-to-square':           faPenToSquare,
  'lightbulb':               faLightbulb,
  'robot':                   faRobot,
  'landmark':                faLandmark,
  'box':                     faBox,
  'briefcase':               faBriefcase,
  'cloud-sun':               faCloudSun,
  'globe':                   faGlobe,
  'rocket':                  faRocket,
  'bullseye':                faBullseye,
  'chart-bar':               faChartBar,
  'chart-simple':            faChartSimple,
  'wrench':                  faWrench,
  'laptop-code':             faLaptopCode,
  'star':                    faStar,
  'inbox':                   faInbox,
  'user-tie':                faUserTie,
  'mug-hot':                 faMugHot,
  'person-running':          faPersonRunning,
  'camera':                  faCamera,
  'book-open':               faBookOpen,
  'gamepad':                 faGamepad,
  'envelope':                faEnvelope,
  'clock':                   faClock,
  'file-lines':              faFileLines,
  'link':                    faLink,
  'arrow-up-right-from-square': faArrowUpRightFromSquare,
  'image':                   faImage,
  'user':                    faUser,
  'folder-open':             faFolderOpen,
  'file':                    faFile,
  'angle-right':             faAngleRight,
  'database':                faDatabase,
  'code':                    faCode,
  'server':                  faServer,
  'layer-group':             faLayerGroup,
  'graduation-cap':          faGraduationCap,
  'heart':                   faHeart,
  'shield-halved':           faShieldHalved,
  'terminal':                faTerminal,
  'palette':                 faPalette,
}

export function getIcon(key: string): IconDefinition {
  return ICON_MAP[key] ?? faPenToSquare
}

export const BLOG_ICON_PRESETS: Array<{ key: string; label: string }> = [
  { key: 'pen-to-square', label: '글쓰기'   },
  { key: 'lightbulb',     label: '아이디어' },
  { key: 'robot',         label: 'AI'       },
  { key: 'rocket',        label: '스타트업' },
  { key: 'landmark',      label: '정책'     },
  { key: 'box',           label: '제품'     },
  { key: 'globe',         label: '웹'       },
  { key: 'bullseye',      label: '전략'     },
  { key: 'chart-bar',     label: '데이터'   },
  { key: 'wrench',        label: '개발'     },
  { key: 'laptop-code',   label: '코딩'     },
  { key: 'star',          label: '리뷰'     },
]
